{
 "title": "CIS k8s Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "#  **CIS Google Kubernetes Engine (GKE) Benchmark**\n---\n         "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "CIS BENCHMARK: Compliantce per category",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum(status)/16*100 as 'CIS CONTROLS 1'\nfrom checks\nWHERE id_policy >= 1 AND id_policy <= 16;\n"
    },
    {
     "rawSql": "select \n  sum(status)/12*100 as 'CIS CONTROLS 2'\nfrom checks\nWHERE id_policy >= 17 AND id_policy <= 28;"
    }
   ]
  },
  {
   "title": "CIS BENCHMARK: Policies implemented",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) \nfrom checks;\n"
    }
   ]
  },
  {
   "title": "CIS BENCHMARK: Global level compliance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select sum(status)/28*100 from checks;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 12 },
   "options": { "content": "\n---\n         " },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "CIS CONTROLS 1: Ownership and access level in config files",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT id_policy as 'Policy ID', policy as 'CIS Policy', status as 'Level Compliance'\nFROM checks\nWHERE id_policy >= 1 AND id_policy <= 16\n\n"
    }
   ]
  },
  {
   "title": "CIS CONTROLS 2: Settings in kubelet-config.yaml file",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT id_policy as 'Policy ID', policy as 'CIS Policy', status as 'Level Compliance'\nFROM checks\nWHERE id_policy >= 17\n"
    }
   ]
  }
 ]
}