---
- name: Connect to cluster
  command: "gcloud --quiet container clusters get-credentials {{ cluster_name }} --zone {{ location }} --project {{ project_id }}"
- name: Create a k8s Hunter DaemonSet
  command: "kubectl apply -f ../../Daemonsets/hunter.yaml"
- name: Create a k8s Hardener DaemonSet
  command: "kubectl apply -f ../../Daemonsets/hardener.yaml"
