---
- name: Update BD cis_k8s
  hosts: ubuntu2
  remote_user: vagrant
  check_mode: false
  tasks:
    - name: Copy file /tmp/hunterExporter.csv
      copy: src=/tmp/hunterExporter.csv dest=/tmp
    - name: Import data to BD
      shell: mysql --user={{ mysql_root_user }} --password={{ mysql_root_password }} cis_k8s < load_data_infile_checks.sql
