---
- name: create a cluster
  gcp_container_cluster:
    name: "{{ cluster_name }}"
    initial_node_count: "{{ initial_node_count }}"
    node_config:
      machine_type: "{{ machine_type }}"
      disk_size_gb: "{{ disk_size_gb }}"
    location: "{{ location }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    state: present
  register: cluster
- name: create a node pool
  gcp_container_node_pool:
    name: "{{ node_pool_name }}"
    initial_node_count: "{{ pool_initial_node_count }}"
    cluster: "{{ cluster }}"
    zone: "{{ location }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: present
